## \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
#server.port=8080
#

#spring:
#  application:
#    name: gulimall-third-party
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.1.244:8848
#      config:
#        server-addr: 192.168.1.244:8848
#
#server:
#  port: 30000